/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author Thongchu
 */
public class SendEmail {
    
    public void sendEmail(String authen, String email ) {
      // Put recipient’s address
      String to = email;

      // Put sender’s address
      String from = "Admin@example.com";
      final String username = "496f1021f20068";//username generated by Mailtrap
      final String password = "958a1ee0968da3";//password generated by Mailtrap

      // Paste host address from the SMTP settings tab in your Mailtrap Inbox
      String host = "smtp.mailtrap.io";

      Properties props = new Properties();
      props.put("mail.smtp.auth", "true");
//      props.put("mail.smtp.ssl.trust", "smtp.gmail.com");// use one of the options in the SMTP settings tab in your Mailtrap Inbox
//      props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
      props.put("mail.smtp.host", host);
      props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox

      // Get the Session object.
      Session session = Session.getInstance(props,
         new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
               return new PasswordAuthentication(username, password);
    }
         });

      try {
    // Create a default MimeMessage object.
    Message message = new MimeMessage(session);

    // Set From: header field
    message.setFrom(new InternetAddress(from));

    // Set To: header field
    message.setRecipients(Message.RecipientType.TO,
               InternetAddress.parse(to));

    // Set Subject: header field
    message.setSubject("My first message with JavaMail");

    // Put the content of your message
    message.setText("Hi "+email+" , your Code is :" +authen);

    // Send message
    Transport.send(message);

    System.out.println("Sent message successfully....");

      } catch (MessagingException e) {
          System.out.println("e"+e);
         throw new RuntimeException(e);
      }
   }
    
}
